config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    root to: "users/registrations#new"
  end

  get 'welcome/index'
  get '/index' => 'secret_code#index'
  post '/generate' => 'secret_code#generate'

  post "api/v1/gitlabel", to: 'api/v1/git_label#new_label' # Accept github webhook
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  belongs_to :user, optional: true

  NumberOfCodes = [1, 10, 20, 50, 100]

  validates :code, presence: true, uniqueness: true

  # Generate unique uuid that should not exists in db
  def self.new_codes(n)
    codes = []
    0..n.times do
      code = SecureRandom.uuid
      exists?(code: code) ? codes << SecureRandom.uuid : codes << code
    end
    codes
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :secret_code, autosave: true, dependent: :destroy

  accepts_nested_attributes_for :secret_code

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/git_label_controller.rb
require 'net/http'
require 'uri'

class Api::V1::GitLabelController < ApplicationController

  def new_label
    logger.debug(params)
    if params[:action].eql?('new_label')
      uri = URI.parse("https://gaurav.requestcatcher.com/test")
      request = Net::HTTP::Post.new(uri)
      request.body = "Label params[:label][:name] was added to issue params[:issue][:url]"

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end
      render json: { success: 'Successfully posted over Slack'  }, status: 200
      logger.debug(response)
    else
      render json: { error: 'Json payload is in wrong format' }, status: 422
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => exception.message }
    end
  end

  protected
    def after_sign_in_path_for(resource)
      welcome_index_path
    end
end

app/controllers/secret_code_controller.rb
class SecretCodeController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @secret_codes = SecretCode.all
  end

  def generate
    @new_codes = SecretCode.new_codes(permitted_params)
  end

  private
    def permitted_params
      params.require(:secret_code).permit(:numbers) ? params[:secret_code][:numbers].to_i : 10
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource
    yield resource if block_given?
    respond_with resource.build_secret_code
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first, :last,
                                                       :secret_code_attributes => :code])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
    if html_tag =~ /\<label/
      html_tag
    else
      errors = Array(instance.error_message).join(',')
      %(#{html_tag}<span class="validation-error">&nbsp;#{errors}</span>).html_safe
    end
  end
end

app/helpers/secret_code_helper.rb
module SecretCodeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sd2labs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <%= link_to 'SD2 Labs Test', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Dashboard", welcome_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% if current_user %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
              <% else %>
                <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
              <% end %>
            </li>
          </ul>
        </div>
      </nav><hr>
      <div class="row">
        <div class="col-12">
          <% if current_user %>
            Signed in as <%= current_user.email %> | <%= link_to "Logout", destroy_user_session_path, method: :delete, data: {:confirm => "You want to logout ?" } %>
          <% end %>
        </div>
      </div>
      <%= flash_messages %>
      <%= yield %>
      <hr><footer class="footer">
        <p>&copy; SD2 Labs test <%= Date.today.year %></p>
      </footer>
    </div>
  </body>
</html>

app/views/secret_code/_new_codes.html.erb
<table class="table table-bordered table-hover table-light">
  <thead>
    <tr>
      <th>New Secret Codes</th>
    </tr>
  </thead>
  <tbody>
    <% @new_codes.each do |code| %>
      <tr>
        <td><%= code %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/secret_code/generate.js.erb
$('#new_codes').html("<%= escape_javascript(render partial: 'new_codes', locals: { result: @new_codes }) %>");

app/views/secret_code/index.html.erb
<div class="row">
  <div class="col-7">
    <% if @secret_codes.present? %>
      <table class="table table-bordered table-hover table-light">
        <thead class="table-primary">
          <tr>
            <th>Email</th>
            <th>Secret Code</th>
          </tr>
        </thead>
        <tbody>
          <% @secret_codes.each do |secret_code| %>
            <tr>
              <td><%= secret_code.user.email %></td>
              <td><%= secret_code.code %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="row justify-content-md-center"><br/><br/>
        <p class="text-primary"><br/><br/>
          Currently, No secret code associated with users.
        </p>
      </div>
    <% end %>
  </div>

  <div class="col-5">
    <h4><p class="text-danger">Generate New Secret Codes</p></h4>
    <%= form_tag(generate_path, method: :post, remote: true) do %>
      <div class="form-group">
        <%= label_tag 'No. of secret codes' %>
        <%= select_tag 'secret_code[numbers]', options_for_select(SecretCode::NumberOfCodes, 10), class: 'form-control' %><br/>
        <%= submit_tag 'Generate', type: 'submit', class: "btn btn-outline-success btn-lg btn-block my-sm-2" %>
      </div>
    <% end %>

    <div id="new_codes">
      <% if @new_codes %>
        <%= render partial: 'new_codes' %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<% if current_user.admin? %>
  <div class="row justify-content-md-center"><br/><br/>
    <p class="text-danger"><br/><br/>
      Check Secret Codes <%= link_to 'here', index_path %><br/><br/>
    </p>
  </div>
<% end %>